[theme]
base = "dark"
baseFontSize = 15
font = "Space Grotesk"
primaryColor = "#FFFFFF"
backgroundColor = "#121212"
secondaryBackgroundColor = "#333333"
textColor = "#FFFFFF"
linkColor = "#9D9D9D"
borderColor = "#5D01EF"
showWidgetBorder = false
baseRadius = "0.3rem"

[theme.sidebar]
backgroundColor = "#000000"
secondaryBackgroundColor = "#333333"
borderColor = "#696969"

[client]
showSidebarNavigation = false
toolbarMode = "minimal"

[ui]
hideTopBar = true